# This workflow will:
#
# 1) Install Python dependencies
# 2) Examines source code formatting and linting
# 3) Run test cases
#
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: RequestsStampede Module Checks

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        operating_system:
          - ubuntu-latest
          - macos-latest
        python_version:
          - 3.7
          - 3.8
          - 3.9
    
    runs-on: ${{ matrix.operating_system }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python Version ${{ matrix.python_verion }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install RequestsStampede python module
        run: |
          pip install .;

      - name: Install development dependencies
        run: |
          pip install --upgrade pip
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Examine source code formatting with black
        run: |
          black --check .;

      - name: Analyze source code with pylint
        run: |
          pylint RequestsStampede/ tests/;

      - name: Test with pytest
        run: |
          pytest
